version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    working_directory: ~/gallery-authentication
    steps:
      # alias for git clone - getting the code
      - checkout 
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Install npm dependencies
          command: npm install --save
      - run:
          name: Build Docker Image
          command: docker build -t tinec/auth:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_ACCESS_TOKEN_TINE" | docker login --username $DOCKERHUB_USERNAME_TINE --password-stdin
            docker push tinec/auth:latest

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build


